[prelude]
types = [
    "std::string::Str",
    "std::string_view::StrView",
    "std::boolean::Bool",
    "std::number::U8",
    "std::number::U16",
    "std::number::U32",
    "std::number::U64",
    "std::number::U128",
    "std::number::U256",
    "std::number::USize",
    "std::number::S8",
    "std::number::S16",
    "std::number::S32",
    "std::number::S64",
    "std::number::S128",
    "std::number::S256",
    "std::number::SSize",
    "std::number::F8",
    "std::number::F16",
    "std::number::F32",
    "std::number::F64",
    "std::number::F128",
    "std::void::Void",
    "std::option::Opt",
    "std::option::None",
    "std::option::Some",
    "std::result::Res",
    "std::result::Pass",
    "std::result::Fail",
    "std::array::Arr",
    "std::vector::Vec",
    "std::slice::Slice",
    "std::tuple::Tup",
    "std::single::Single",
    "std::function::FunRef",
    "std::function::FunMut",
    "std::function::FunMov",
    "std::cast::From",
    "std::annotations::annotation",
    "std::annotations::public",
    "std::annotations::protected",
    "std::annotations::private",
    "std::annotations::virtual_method",
    "std::annotations::abstract_method",
    "std::annotations::ffi",
]